### ISSUE TITLE
upgrade to allow for 20 private repositories

### ISSUE THREAD

**Issue by cortfritz** [ksidatasciences/general#2]
@ksi-mgrice please do this.

**Comment by ksi-mgrice** [comment]
Per our github training session, I have upgraded our plan to the Silver Level ($50 per month for 20 repositories). Approved by @KSI-jgaster .

**Comment by cortfritz** [comment]
gunna close

**Comment by cortfritz** [comment]
oops didn't mean to do that

**Comment by KSI-jgaster** [comment]
OK let's get this closed
